# TODO: explain it
name: know_my_band_loco

# TODO: explain it
# subdomain: sample

# TODO: explain it
# domains: [www.example.com, example.com]

# TODO: explain it
locales: [en]

# TODO: explain it
seo_title: know_my_band_loco
meta_keywords: "some meta keywords"
meta_description: "some meta description"